#pragma once

#include "../common.h"

namespace libmcc {

class c_game_event_manager : public i_game_event_manager {
public:
	c_game_event_manager();

	bool AchievementEarned(const wchar_t* xuid, const GUID* guid, const wchar_t*, int) override;
	bool AshesToAshes(const wchar_t* xuid, const GUID* guid) override;
	bool Assist(const wchar_t* xuid, int, const GUID* guid, const wchar_t*, int, int, const GUID*, int, int, int, int, int, int, int, int, const wchar_t*, int, int, int, int) override;
	bool AudioLogClaimed(const wchar_t* xuid, const GUID* guid, int) override;
	bool Base(const wchar_t* xuid, const GUID* guid) override;
	void Base(const wchar_t* xuid, int a3, const GUID* a4, const wchar_t* a5, int a6, int a7, const GUID* a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, const wchar_t* a17, int a18, int a19, int a20, int a21) override;
	bool BIFactControllerSettings(const wchar_t* xuid, const GUID* guid, int a4, const wchar_t* a5, int a6, int a7, int a8) override;
	bool BIFactDeepLink(const wchar_t* xuid, const GUID* guid) override;
	bool BIFactDeepLinkRecieve(const wchar_t* xuid, const GUID* guid, const wchar_t*, const wchar_t*) override;
	bool BIFactDeepLinkSend(const wchar_t* xuid, const GUID* guid, const wchar_t*, const wchar_t*) override;
	bool BIFactDualWield(const wchar_t* xuid, const GUID* guid, int, const wchar_t*, int, int, int, const void*) override;
	bool BIFactGameSession(const wchar_t* a2, const GUID* a3, const void* a4, const void* a5, const wchar_t* a6, const void* a7, const void* a8, int a9, const wchar_t* a10, int a11, int a12, const void* a13, const wchar_t* a14, int a15, int a16, int a17, const void* a18, int a19, int a20, const void* a21, const void* a22, int a23, int a24, int a25, int a26, int a27, int a28, int a29) override;
	bool BIFactLoadout(const wchar_t* xuid, const GUID* guid, int a4, const wchar_t* a5, int a6, int a7, int a8, int a9, int a10) override;
	bool BIFactMatchmaking(const wchar_t* xuid, const GUID* guid, int a4, const wchar_t* a5, const void* a6, int a7, const void* a8, int a9, const void* a10, int a11, int a12, const GUID* a13) override;
	bool BIFactMatchmakingDetails(const wchar_t* xuid, const GUID* guid, int a4, int a5, int a6, int a7, int a8, const void* a9, const void* a10, int a11, const wchar_t* a12, int a13, int a14, int a15, int a16) override;
	bool BIFactMedia(const wchar_t* xuid, const GUID* guid, int a4, const wchar_t* a5, const void* a6, int a7, const void* a8, const wchar_t* a9) override;
	bool BirdOfPrey(const wchar_t* xuid, const GUID* guid) override;
	bool BitsAndPiecesDestroyed(const wchar_t* xuid, const GUID* guid) override;
	void BroadcastingAssist(const wchar_t* xuid, const GUID* guid, const void* a4, unsigned int a5) override;
	void BroadcastingDeath(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingHeartbeat(const wchar_t* xuid, const GUID* guid, const void*) override;
	bool BroadcastingKill(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingMatchEnd(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingMatchRoundEnd(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingMatchRoundStart(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingMatchStart(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingMedal(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingPlayerJoined(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingPlayerLeft(const wchar_t* xuid, const GUID* guid) override;
	bool BroadcastingPlayerSpawn(const wchar_t* xuid, const GUID* guid) override;
	void BroadcastingPlayerSwitchedTeams(const wchar_t* xuid, const GUID*, const FILETIME*, int index, int) override;
	void BroadcastingScore(const wchar_t* xuid, const GUID*, int index, const FILETIME*, int, int, int, int) override;
	bool BroadcastingStart(const wchar_t* xuid, const GUID* guid) override;
	bool CampaignDifficulty(const wchar_t* xuid, const GUID* guid, const wchar_t*, const wchar_t*) override;
	bool ChallengeCompleted(const wchar_t* xuid, const GUID* guid, const wchar_t*, int) override;
	bool ClassicModeSwitched(const wchar_t* xuid, const GUID* guid, int) override;
	bool CleverGirl(const wchar_t* xuid, const GUID* guid) override;
	bool ClueClaimed(const wchar_t* xuid, const GUID* guid, int) override;
	bool CompletionCount(const wchar_t* xuid, const GUID* guid, int) override;
	bool CoopMissionCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool CoopSpartanOpsMissionCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool Customization(const wchar_t* xuid, const GUID* guid) override;
	bool DashboardContext(const wchar_t* xuid, const GUID* guid) override;
	bool Death(const wchar_t* xuid, const GUID* guid) override;
	bool DollFound(const wchar_t* xuid, const GUID* guid) override;
	bool EliteWin(const wchar_t* xuid, const GUID* guid) override;
	bool Emblem(const wchar_t* xuid, const GUID* guid) override;
	bool EnemyDefeated(const wchar_t* xuid, const GUID* guid) override;
	bool FriendsBestedOnHeroLeaderboard(const wchar_t* xuid, const GUID* guid) override;
	bool GameProgress(const wchar_t* xuid, const GUID* guid) override;
	bool GameVarSaved(const wchar_t* xuid, const GUID* guid) override;
	bool GrenadeStick(const wchar_t* xuid, const GUID* guid) override;
	bool HelloNurse(const wchar_t* xuid, const GUID* guid) override;
	bool InGamePresence(const wchar_t* xuid, const GUID* guid) override;
	bool ISeeYou(const wchar_t* xuid, const GUID* guid) override;
	bool Joinability(const wchar_t* xuid, const GUID* guid) override;
	bool Lobby(const wchar_t* xuid, const GUID* guid) override;
	bool MainMenuPresence(const wchar_t* xuid, const GUID* guid) override;
	bool MapVarSaved(const wchar_t* xuid, const GUID* guid) override;
	bool MatchmakingHopper(const wchar_t* xuid, const GUID* guid) override;
	bool MediaUsage(const wchar_t* xuid, const GUID* guid) override;
	bool MeldOfferPresented(const wchar_t* xuid, const GUID* guid) override;
	bool MeldOfferResponded(const wchar_t* xuid, const GUID* guid) override;
	bool MeldPageAction(const wchar_t* xuid, const GUID* guid) override;
	bool MeldPageView(const wchar_t* xuid, const GUID* guid) override;
	bool MissionCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool MortardomWraithsKilled(const wchar_t* xuid, const GUID* guid) override;
	bool MultiplayerGameEngine(const wchar_t* xuid, const GUID* guid) override;
	bool MultiplayerMap(const wchar_t* xuid, const GUID* guid) override;
	bool MultiplayerRoundEnd(const wchar_t* xuid, const GUID* guid) override;
	bool MultiplayerRoundStart(const wchar_t* xuid, const GUID* guid) override;
	bool NappersCaught(const wchar_t* xuid, const GUID* guid) override;
	bool NewsStoryRead(const wchar_t* xuid, const GUID* guid) override;
	bool ObjectiveEnd(const wchar_t* xuid, const GUID* guid) override;
	bool ObjectiveStart(const wchar_t* xuid, const GUID* guid) override;
	bool PageAction(const wchar_t* xuid, const GUID* guid) override;
	bool PageView(const wchar_t* xuid, const GUID* guid) override;
	bool PhantomHunter(const wchar_t* xuid, const GUID* guid) override;
	bool PigsCanFly(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerCheckedInToday(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerDefeated(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerGameResults(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerGameResultsDamageStat(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerGameResultsGriefingStat(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerGameResultsGriefingStats(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerGameResultsInterestStats(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerGameResultsMedal(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerSessionEnd(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerSessionPause(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerSessionResume(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerSessionStart(const wchar_t* xuid, const GUID* guid) override;
	bool PlayerSpawned(const wchar_t* xuid, const GUID* guid) override;
	bool PlaylistCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool PlaylistProgress(const wchar_t* xuid, const GUID* guid) override;
	bool RankedStatsDNFInfo(const wchar_t* xuid, const GUID* guid) override;
	bool RankedStatsOverride(const wchar_t* xuid, const GUID* guid) override;
	bool RankedStatsPenalty(const wchar_t* xuid, const GUID* guid) override;
	bool RankedStatsUpdate(const wchar_t* xuid, const GUID* guid) override;
	bool RankedUpSpartanIv(const wchar_t* xuid, const GUID* guid) override;
	bool RealtimeFlagCaptured(const wchar_t* xuid, const GUID* guid) override;
	bool RealtimeMedal(const wchar_t* xuid, const GUID* guid) override;
	bool RealtimePilotedVehicle(const wchar_t* xuid, const GUID* guid) override;
	bool RivalID(const wchar_t* xuid, const GUID* guid) override;
	bool SectionEnd(const wchar_t* xuid, const GUID* guid) override;
	bool SectionStart(const wchar_t* xuid, const GUID* guid) override;
	bool SectionStats(const wchar_t* xuid, const GUID* guid) override;
	bool SessionSizeUpdate(const wchar_t* xuid, const GUID* guid) override;
	bool SizeIsEverything(const wchar_t* xuid, const GUID* guid) override;
	bool SkeetShooter(const wchar_t* xuid, const GUID* guid) override;
	bool SkullClaimed(const wchar_t* xuid, const GUID* guid) override;
	bool SoloMissionCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool SoloSpartanOpsMissionCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool SpartanOpsMissionCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool Supercombine(const wchar_t* xuid, const GUID* guid) override;
	bool SurvivalSpace(const wchar_t* xuid, const GUID* guid) override;
	bool TerminalFound(const wchar_t* xuid, const GUID* guid) override;
	bool TerminalId(const wchar_t* xuid, const GUID* guid) override;
	bool TicketsEarned(const wchar_t* xuid, const GUID* guid) override;
	bool TitleCompleted(const wchar_t* xuid, const GUID* guid) override;
	bool TitleLaunched(const wchar_t* xuid, const GUID* guid) override;
	bool ValhallaSign(const wchar_t* xuid, const GUID* guid) override;
	bool ViewOffer(const wchar_t* xuid, const GUID* guid) override;
	bool VIPStatusEarned(const wchar_t* xuid, const GUID* guid) override;
	bool WhatAboutTanksDestroyed(const wchar_t* xuid, const GUID* guid) override;
	bool WonWarGame(const wchar_t* xuid, const GUID* guid) override;
	bool ZanzibarSign(const wchar_t* xuid, const GUID* guid) override;
	bool FirefightGameResults(const wchar_t* xuid, const GUID* guid) override;
	bool ScavengerHuntObjectFound(const wchar_t* xuid, const GUID* guid) override;
	void _() override;
	void __() override;
	void ___() override;
	void ____() override;
	void _____() override;
	void ______() override;
	void _______() override;
	void ________() override;
	void _________() override;
	void __________() override;
	int ___________() override;
	void SetBoolTrue() override;
	void SetBoolFalse() override;
	bool GetBool() override;
	void SetBool(bool, bool) override;
	void MetaGameUpdateGameTicks(float game_ticks) override;
	void GameResultUpdatePlayerTime(int player, float time) override;
	void _____________(bool) override;
	bool MetaGameGetFlags() override;
	GUID* GetGUID() override;
	void ______________(bool*) override;
	void _______________() override;
	void ________________() override;

private:
		GUID m_guid;
};
}

inline static libmcc::c_game_event_manager g_game_event_manager;
inline libmcc::i_game_event_manager* game_event_manager() {
	return &g_game_event_manager;
}
